sudo: false

stages:
  - lint
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: lint
      language: node_js
      node_js: "10"
      script: ./scripts/ci/lint.sh

    - stage: test
      sudo: required
      services:
        -docker
      script: ./scripts/ci/test.sh

    - stage: deploy
      sudo: required
      services:
        -docker
      script: ./scripts/ci/deploy.sh
