sudo: required

language: node
node_js:
  - "10"

services:
  - docker

stages:
  - lint
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: lint
      node_js: "10"
      script: ./scripts/ci/lint

    - stage: test
      node_js: "10"
      script: ./scripts/ci/test

    - stage: deploy
      script: ./scripts/ci/deploy "${TRAVIS_COMMIT::12}"
