sudo: required

language: node_js
node_js: "10"

services:
  - docker

stages:
  - lint
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: lint
      script: ./scripts/ci/lint

    - stage: test
      script: ./scripts/ci/test

    - stage: deploy
      script: ./scripts/ci/deploy
