version: '3'
services:
  node1:
    build:
      context: .
      dockerfile: dev.dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./node_data/1:/usr/src/app/node_data
    ports:
      - "4000:4000"
      - "4100:4100"
    environment:
      - GRAPHQL_SERVER_PORT=4000
      - P2P_SERVER_PORT=4100
      - P2P_NODE_URL=ws://node1:4100
      - PERSISTENCE_PATH=node_data/1

  node2:
    build:
      context: .
      dockerfile: dev.dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./node_data/2:/usr/src/app/node_data
    ports:
      - "4001:4001"
      - "4101:4101"
    environment:
      - GRAPHQL_SERVER_PORT=4001
      - P2P_SERVER_PORT=4101
      - P2P_NODE_URL=ws://node2:4101
      - PERSISTENCE_PATH=node_data/2

  node3:
    build:
      context: .
      dockerfile: dev.dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./node_data/3:/usr/src/app/node_data
    ports:
      - "4002:4002"
      - "4102:4102"
    environment:
      - GRAPHQL_SERVER_PORT=4002
      - P2P_SERVER_PORT=4102
      - P2P_NODE_URL=ws://node3:4102
      - PERSISTENCE_PATH=node_data/3
