version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10@sha256:c773fee595fe7848b60b414a8b2b390d62dd0e224bdb874c82642be7e7a025da
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # Fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test
