#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset
[[ "${DEBUG:-false}" == "true" ]] && set -o xtrace

readonly __script_path="${BASH_SOURCE[0]}"
readonly __dir="$(cd "$(dirname "${__script_path}")" && pwd)"
readonly __file="${__dir}/$(basename "${__script_path}")"
readonly __base="$(basename "${__file}" .sh)"
readonly __root="$(cd "$(dirname "${__dir}")" && pwd)"

readonly image_name="bottlecap_test"

build_docker_image() {
    docker build --file dev.dockerfile \
         --tag "${image_name}" \
         .
}

run_tests() {
    docker run \
        --rm "${image_name}" \
        -e CI \
        -e CODECOV_TOKEN \
        yarn test:ci
}

main() {
    build_docker_image
    run_tests
}

main
